"""empty message

Revision ID: 00705e6c8e09
Revises: 91b4f3722230
Create Date: 2025-02-23 18:45:47.826273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00705e6c8e09"
down_revision: Union[str, None] = "91b4f3722230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages_to_chat_association",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("message_id", "chat_id"),
    )
    op.drop_table("message_to_chat_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_to_chat_association",
        sa.Column(
            "message_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "chat_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
            name="message_to_chat_association_chat_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name="message_to_chat_association_message_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "message_id", "chat_id", name="message_to_chat_association_pkey"
        ),
    )
    op.drop_table("messages_to_chat_association")
    # ### end Alembic commands ###
