"""empty message

Revision ID: 0ff6b09aaf16
Revises: 8d4517c32052
Create Date: 2025-02-23 18:09:54.988076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ff6b09aaf16"
down_revision: Union[str, None] = "8d4517c32052"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beatpack_to_beat_association",
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.Column("beatpack_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
        ),
        sa.PrimaryKeyConstraint("beat_id", "beatpack_id"),
    )
    op.drop_table("beatpack_to_beat_association_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beatpack_to_beat_association_table",
        sa.Column(
            "beat_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "beatpack_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
            name="beatpack_to_beat_association_table_beat_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
            name="beatpack_to_beat_association_table_beatpack_id_fkey",
        ),
    )
    op.drop_table("beatpack_to_beat_association")
    # ### end Alembic commands ###
