"""empty message

Revision ID: 1af67a47f66a
Revises: 648f69718ea4
Create Date: 2025-02-23 18:17:07.733943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1af67a47f66a"
down_revision: Union[str, None] = "648f69718ea4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author_to_licenses_association",
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("license_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["license_id"],
            ["licenses.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "license_id"),
    )
    op.drop_table("user_to_licenses_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_to_licenses_association",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "license_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["license_id"],
            ["licenses.id"],
            name="user_to_licenses_association_license_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_to_licenses_association_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "license_id", name="user_to_licenses_association_pkey"
        ),
    )
    op.drop_table("author_to_licenses_association")
    # ### end Alembic commands ###
