"""empty message

Revision ID: 1b9efddd8d6a
Revises: fccf6218be90
Create Date: 2025-02-26 14:52:08.066205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b9efddd8d6a"
down_revision: Union[str, None] = "fccf6218be90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_to_artist_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track_to_artist_association",
        sa.Column(
            "artist_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "track_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
            name="track_to_artist_association_artist_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name="track_to_artist_association_track_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "artist_id", "track_id", name="track_to_artist_association_pkey"
        ),
    )
    # ### end Alembic commands ###
