"""empty message

Revision ID: 92353adc8146
Revises: c8d768c3774e
Create Date: 2025-02-12 15:31:07.576515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92353adc8146"
down_revision: Union[str, None] = "c8d768c3774e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("artist_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("producer_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "users", "producer_profiles", ["producer_id"], ["id"]
    )
    op.create_foreign_key(
        None, "users", "artist_profiles", ["artist_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "producer_id")
    op.drop_column("users", "artist_id")
    # ### end Alembic commands ###
