"""empty message

Revision ID: 9bb7db0c75c0
Revises: 48672fb1af33
Create Date: 2025-02-23 18:40:21.434524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bb7db0c75c0"
down_revision: Union[str, None] = "48672fb1af33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists_to_tags_association",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "tag_id"),
    )
    op.create_table(
        "artists_to_track_association",
        sa.Column("artist_profile_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_profile_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("artist_profile_id", "track_id"),
    )
    op.create_table(
        "beatpacks_to_tags_association",
        sa.Column("beatpack_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("beatpack_id", "tag_id"),
    )
    op.create_table(
        "producers_to_beatpacks_association",
        sa.Column("producer_profile_id", sa.Integer(), nullable=False),
        sa.Column("beatpack_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_profile_id"],
            ["producer_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("producer_profile_id", "beatpack_id"),
    )
    op.create_table(
        "producers_to_soundkits_association",
        sa.Column("soundkit_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["soundkit_id"],
            ["soundkits.id"],
        ),
        sa.PrimaryKeyConstraint("soundkit_id", "producer_id"),
    )
    op.create_table(
        "producers_to_squads_association",
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column("squad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["squad_id"],
            ["squads.id"],
        ),
        sa.PrimaryKeyConstraint("producer_id", "squad_id"),
    )
    op.create_table(
        "producers_to_tags_association",
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("producer_id", "tag_id"),
    )
    op.create_table(
        "followers_to_artists_association",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "artist_id"),
    )
    op.create_table(
        "followers_to_producers_association",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "producer_id"),
    )
    op.create_table(
        "saver_to_albums_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "album_id"),
    )
    op.create_table(
        "author_to_messages_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "message_id"),
    )
    op.drop_table("artist_to_tags_association")
    op.drop_table("beatpack_to_tag_association")
    op.drop_table("producer_to_squad_association")
    op.drop_table("user_to_message_association")
    op.drop_table("user_to_albums_association")
    op.drop_table("producer_to_tags_association")
    op.drop_table("artist_to_track_association")
    op.drop_table("follower_to_artist_association")
    op.drop_table("producer_to_beatpacks_association")
    op.drop_table("follower_to_producer_association")
    op.drop_table("producer_to_soundkits_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "producer_to_soundkits_association",
        sa.Column(
            "soundkit_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "producer_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
            name="producer_to_soundkits_association_producer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["soundkit_id"],
            ["soundkits.id"],
            name="producer_to_soundkits_association_soundkit_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "soundkit_id",
            "producer_id",
            name="producer_to_soundkits_association_pkey",
        ),
    )
    op.create_table(
        "follower_to_producer_association",
        sa.Column(
            "follower_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "producer_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name="follower_to_producer_association_follower_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
            name="follower_to_producer_association_producer_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "follower_id",
            "producer_id",
            name="follower_to_producer_association_pkey",
        ),
    )
    op.create_table(
        "producer_to_beatpacks_association",
        sa.Column(
            "producer_profile_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "beatpack_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
            name="producer_to_beatpacks_association_beatpack_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["producer_profile_id"],
            ["producer_profiles.id"],
            name="producer_to_beatpacks_association_producer_profile_id_fkey",
        ),
    )
    op.create_table(
        "follower_to_artist_association",
        sa.Column(
            "follower_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "artist_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
            name="follower_to_artist_association_artist_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name="follower_to_artist_association_follower_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "follower_id",
            "artist_id",
            name="follower_to_artist_association_pkey",
        ),
    )
    op.create_table(
        "artist_to_track_association",
        sa.Column(
            "artist_profile_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "track_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["artist_profile_id"],
            ["artist_profiles.id"],
            name="artist_to_track_association_artist_profile_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name="artist_to_track_association_track_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "artist_profile_id",
            "track_id",
            name="artist_to_track_association_pkey",
        ),
    )
    op.create_table(
        "producer_to_tags_association",
        sa.Column(
            "producer_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
            name="producer_to_tags_association_producer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name="producer_to_tags_association_tag_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "producer_id", "tag_id", name="producer_to_tags_association_pkey"
        ),
    )
    op.create_table(
        "user_to_albums_association",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "album_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
            name="user_to_albums_association_album_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_to_albums_association_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "album_id", name="user_to_albums_association_pkey"
        ),
    )
    op.create_table(
        "user_to_message_association",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "message_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name="user_to_message_association_message_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_to_message_association_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "message_id", name="user_to_message_association_pkey"
        ),
    )
    op.create_table(
        "producer_to_squad_association",
        sa.Column(
            "producer_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "squad_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
            name="producer_to_squad_association_producer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["squad_id"],
            ["squads.id"],
            name="producer_to_squad_association_squad_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "producer_id",
            "squad_id",
            name="producer_to_squad_association_pkey",
        ),
    )
    op.create_table(
        "beatpack_to_tag_association",
        sa.Column(
            "beatpack_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
            name="beatpack_to_tag_association_beatpack_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name="beatpack_to_tag_association_tag_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "beatpack_id", "tag_id", name="beatpack_to_tag_association_pkey"
        ),
    )
    op.create_table(
        "artist_to_tags_association",
        sa.Column(
            "artist_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
            name="artist_to_tags_association_artist_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name="artist_to_tags_association_tag_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "artist_id", "tag_id", name="artist_to_tags_association_pkey"
        ),
    )
    op.drop_table("author_to_messages_association")
    op.drop_table("saver_to_albums_association")
    op.drop_table("followers_to_producers_association")
    op.drop_table("followers_to_artists_association")
    op.drop_table("producers_to_tags_association")
    op.drop_table("producers_to_squads_association")
    op.drop_table("producers_to_soundkits_association")
    op.drop_table("producers_to_beatpacks_association")
    op.drop_table("beatpacks_to_tags_association")
    op.drop_table("artists_to_track_association")
    op.drop_table("artists_to_tags_association")
    # ### end Alembic commands ###
