"""empty message

Revision ID: 9e7f0f4fdf95
Revises: 9bb7db0c75c0
Create Date: 2025-02-23 18:40:26.875440

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e7f0f4fdf95"
down_revision: Union[str, None] = "9bb7db0c75c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
