"""empty message

Revision ID: c80ab47270a4
Revises: b0f74bd72dde
Create Date: 2025-02-12 15:11:42.554772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c80ab47270a4"
down_revision: Union[str, None] = "b0f74bd72dde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track_to_artist_association",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "track_id"),
    )
    op.add_column(
        "artist_profiles",
        sa.Column("is_available", sa.Boolean(), nullable=False),
    )
    op.alter_column(
        "artist_profiles",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "artist_profiles",
        "picture_url",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_constraint(
        "artist_profiles_user_id_fkey", "artist_profiles", type_="foreignkey"
    )
    op.drop_column("artist_profiles", "user_id")
    op.alter_column(
        "beatpack_to_beat_association_table",
        "beat_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "beatpack_to_beat_association_table",
        "beatpack_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.add_column(
        "producer_profiles",
        sa.Column("is_available", sa.Boolean(), nullable=False),
    )
    op.drop_constraint(
        "producer_profiles_user_id_fkey",
        "producer_profiles",
        type_="foreignkey",
    )
    op.drop_column("producer_profiles", "user_id")
    op.alter_column(
        "producer_to_beatpacks_association",
        "producer_profile_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "producer_to_beatpacks_association",
        "beatpack_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "producer_to_beatpacks_association",
        "beatpack_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "producer_to_beatpacks_association",
        "producer_profile_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.add_column(
        "producer_profiles",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "producer_profiles_user_id_fkey",
        "producer_profiles",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_column("producer_profiles", "is_available")
    op.alter_column(
        "beatpack_to_beat_association_table",
        "beatpack_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "beatpack_to_beat_association_table",
        "beat_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.add_column(
        "artist_profiles",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "artist_profiles_user_id_fkey",
        "artist_profiles",
        "users",
        ["user_id"],
        ["id"],
    )
    op.alter_column(
        "artist_profiles",
        "picture_url",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "artist_profiles",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("artist_profiles", "is_available")
    op.drop_table("track_to_artist_association")
    # ### end Alembic commands ###
