"""empty message

Revision ID: d5c523a95577
Revises: 5aae5823ec2a
Create Date: 2025-02-23 17:56:28.921220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5c523a95577"
down_revision: Union[str, None] = "5aae5823ec2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follower_to_producer_association",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "producer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("follower_to_producer_association")
    # ### end Alembic commands ###
