"""empty message

Revision ID: e5309f7b68c3
Revises: 0ff6b09aaf16
Create Date: 2025-02-23 18:14:15.166134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5309f7b68c3"
down_revision: Union[str, None] = "0ff6b09aaf16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saver_to_playlists_association",
        sa.Column("saver_id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["saver_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("saver_id", "playlist_id"),
    )
    op.drop_table("user_to_playlists_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_to_playlists_association",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "playlist_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
            name="user_to_playlists_association_playlist_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_to_playlists_association_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "playlist_id", name="user_to_playlists_association_pkey"
        ),
    )
    op.drop_table("saver_to_playlists_association")
    # ### end Alembic commands ###
