"""empty message

Revision ID: fccf6218be90
Revises: 187682ad9106
Create Date: 2025-02-26 14:10:47.267680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fccf6218be90"
down_revision: Union[str, None] = "187682ad9106"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follower   _to_tag_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "tag_id"),
    )
    op.drop_table("user_to_tag_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_to_tag_association",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name="user_to_tag_association_tag_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_to_tag_association_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "tag_id", name="user_to_tag_association_pkey"
        ),
    )
    op.drop_table("follower   _to_tag_association")
    # ### end Alembic commands ###
